#include <common.h>
#include <sview/sview.h>
#include <sview/sview_utils.h>

const char *sview_type_strings[SVIEW_NUMS] = {
	[SVIEW_PIC]                     = "SVIEW_PIC",
	[SVIEW_NUM]                     = "SVIEW_NUM",
	[SVIEW_LINEAR_LAYOUT]           = "SVIEW_LINEAR_LAYOUT",
	[SVIEW_ABSOLUTE_LAYOUT]         = "SVIEW_ABSOLUTE_LAYOUT",
	[SVIEW_FRAME_LAYOUT]            = "SVIEW_FRAME_LAYOUT",
	[SVIEW_TIME_NUM]                = "SVIEW_TIME_NUM",
	[SVIEW_SECOND_L]                = "SVIEW_SECOND_L",
	[SVIEW_SECOND_H]                = "SVIEW_SECOND_H",
	[SVIEW_MINUTE_L]                = "SVIEW_MINUTE_L",
	[SVIEW_MINUTE_H]                = "SVIEW_MINUTE_H",
	[SVIEW_HOUR_L]                  = "SVIEW_HOUR_L",
	[SVIEW_HOUR_H]                  = "SVIEW_HOUR_H",
	[SVIEW_DAY_L]                   = "SVIEW_DAY_L",
	[SVIEW_DAY_H]                   = "SVIEW_DAY_H",
	[SVIEW_WEEK]                    = "SVIEW_WEEK",
	[SVIEW_MONTH_L]                 = "SVIEW_MONTH_L",
	[SVIEW_MONTH_H]                 = "SVIEW_MONTH_H",
	[SVIEW_YEAR0]                   = "SVIEW_YEAR0",
	[SVIEW_YEAR1]                   = "SVIEW_YEAR1",
	[SVIEW_YEAR2]                   = "SVIEW_YEAR2",
	[SVIEW_YEAR3]                   = "SVIEW_YEAR3",
	[SVIEW_ROTATE_PIC]              = "SVIEW_ROTATE_PIC",
	[SVIEW_ANALOG_TIME]             = "SVIEW_ANALOG_TIME",
	[SVIEW_ANALOG_SECOND]           = "SVIEW_ANALOG_SECOND",
	[SVIEW_ANALOG_MINUTE]           = "SVIEW_ANALOG_MINUTE",
	[SVIEW_ANALOG_HOUR]             = "SVIEW_ANALOG_HOUR",
	[SVIEW_ANALOG_DAY]              = "SVIEW_ANALOG_DAY",
	[SVIEW_ANALOG_WEEK]             = "SVIEW_ANALOG_WEEK",
	[SVIEW_ANALOG_MONTH]            = "SVIEW_ANALOG_MONTH",
	[SVIEW_ANALOG_AM_PM]            = "SVIEW_ANALOG_AM_PM",
	[SVIEW_ANALOG_HOUR_WITH_MINUTE] = "SVIEW_ANALOG_HOUR_WITH_MINUTE",
};

const char *sview_type_short_strings[SVIEW_NUMS] = {
	[SVIEW_PIC]                     = "pic",
	[SVIEW_NUM]                     = "num",
	[SVIEW_LINEAR_LAYOUT]           = "linear_layout",
	[SVIEW_ABSOLUTE_LAYOUT]         = "absolute_layout",
	[SVIEW_FRAME_LAYOUT]            = "frame_layout",
	[SVIEW_TIME_NUM]                = "time_num",
	[SVIEW_SECOND_L]                = "second_l",
	[SVIEW_SECOND_H]                = "second_h",
	[SVIEW_MINUTE_L]                = "minute_l",
	[SVIEW_MINUTE_H]                = "minute_h",
	[SVIEW_HOUR_L]                  = "hour_l",
	[SVIEW_HOUR_H]                  = "hour_h",
	[SVIEW_DAY_L]                   = "day_l",
	[SVIEW_DAY_H]                   = "day_h",
	[SVIEW_WEEK]                    = "week",
	[SVIEW_MONTH_L]                 = "month_l",
	[SVIEW_MONTH_H]                 = "month_h",
	[SVIEW_YEAR0]                   = "year0",
	[SVIEW_YEAR1]                   = "year1",
	[SVIEW_YEAR2]                   = "year2",
	[SVIEW_YEAR3]                   = "year3",
	[SVIEW_ROTATE_PIC]              = "rotate_pic",
	[SVIEW_ANALOG_TIME]             = "analog_time",
	[SVIEW_ANALOG_SECOND]           = "analog_second",
	[SVIEW_ANALOG_MINUTE]           = "analog_minute",
	[SVIEW_ANALOG_HOUR]             = "analog_hour",
	[SVIEW_ANALOG_DAY]              = "analog_day",
	[SVIEW_ANALOG_WEEK]             = "analog_week",
	[SVIEW_ANALOG_MONTH]            = "analog_month",
	[SVIEW_ANALOG_AM_PM]            = "analog_am_pm",
	[SVIEW_ANALOG_HOUR_WITH_MINUTE] = "analog_hour_with_minute",
};
