/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ingenic_iwds_slpt_view_SlptView */

#ifndef _Included_com_ingenic_iwds_slpt_view_SlptView
#define _Included_com_ingenic_iwds_slpt_view_SlptView
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ingenic_iwds_slpt_view_SlptView_ALIGN_NULL
#define com_ingenic_iwds_slpt_view_SlptView_ALIGN_NULL 0L
#undef com_ingenic_iwds_slpt_view_SlptView_ALIGN_CENTER_HORIZONTAL
#define com_ingenic_iwds_slpt_view_SlptView_ALIGN_CENTER_HORIZONTAL 1L
#undef com_ingenic_iwds_slpt_view_SlptView_ALIGN_CENTER_VERTICAL
#define com_ingenic_iwds_slpt_view_SlptView_ALIGN_CENTER_VERTICAL 2L
#undef com_ingenic_iwds_slpt_view_SlptView_ALIGN_CENTER_HOR_VER
#define com_ingenic_iwds_slpt_view_SlptView_ALIGN_CENTER_HOR_VER 3L
#undef com_ingenic_iwds_slpt_view_SlptView_DEFAULT_SIZE
#define com_ingenic_iwds_slpt_view_SlptView_DEFAULT_SIZE 30L
/*
 * Class:     com_ingenic_iwds_slpt_view_SlptView
 * Method:    createJniView
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ingenic_iwds_slpt_view_SlptView_createJniView
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_ingenic_iwds_slpt_view_SlptView
 * Method:    syncViewMember
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_ingenic_iwds_slpt_view_SlptView_syncViewMember__JLjava_lang_String_2I
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     com_ingenic_iwds_slpt_view_SlptView
 * Method:    syncViewMember
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ingenic_iwds_slpt_view_SlptView_syncViewMember__JLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_ingenic_iwds_slpt_view_SlptView
 * Method:    initSlptJni
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ingenic_iwds_slpt_view_SlptView_initSlptJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
