/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ingenic_iwds_slpt_SlptClock */

#ifndef _Included_com_ingenic_iwds_slpt_SlptClock
#define _Included_com_ingenic_iwds_slpt_SlptClock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ingenic_iwds_slpt_SlptClock
 * Method:    initSlpt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ingenic_iwds_slpt_SlptClock_initSlpt
  (JNIEnv *, jclass);

/*
 * Class:     com_ingenic_iwds_slpt_SlptClock
 * Method:    enableSlpt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ingenic_iwds_slpt_SlptClock_enableSlpt
  (JNIEnv *, jclass);

/*
 * Class:     com_ingenic_iwds_slpt_SlptClock
 * Method:    disableSlpt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ingenic_iwds_slpt_SlptClock_disableSlpt
  (JNIEnv *, jclass);

/*
 * Class:     com_ingenic_iwds_slpt_SlptClock
 * Method:    setBrightnessOfSlpt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ingenic_iwds_slpt_SlptClock_setBrightnessOfSlpt
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ingenic_iwds_slpt_SlptClock
 * Method:    requestSlptDisplayPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ingenic_iwds_slpt_SlptClock_requestSlptDisplayPause
  (JNIEnv *, jclass);

/*
 * Class:     com_ingenic_iwds_slpt_SlptClock
 * Method:    requestSlptDisplayResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ingenic_iwds_slpt_SlptClock_requestSlptDisplayResume
  (JNIEnv *, jclass);

/*
 * Class:     com_ingenic_iwds_slpt_SlptClock
 * Method:    initSview
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ingenic_iwds_slpt_SlptClock_initSview__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ingenic_iwds_slpt_SlptClock
 * Method:    initSview
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_ingenic_iwds_slpt_SlptClock_initSview___3B
  (JNIEnv *, jclass, jbyteArray );

#ifdef __cplusplus
}
#endif
#endif
