/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ingenic_iwds_slpt_view_core_Picture_PictureContainer */

#ifndef _Included_com_ingenic_iwds_slpt_view_core_Picture_PictureContainer
#define _Included_com_ingenic_iwds_slpt_view_core_Picture_PictureContainer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ingenic_iwds_slpt_view_core_Picture_PictureContainer
 * Method:    clearPictureGroup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ingenic_iwds_slpt_view_core_Picture_00024PictureContainer_clearPictureGroup
  (JNIEnv *, jclass);

/*
 * Class:     com_ingenic_iwds_slpt_view_core_Picture_PictureContainer
 * Method:    addPictureGroup
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ingenic_iwds_slpt_view_core_Picture_00024PictureContainer_addPictureGroup
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ingenic_iwds_slpt_view_core_Picture_PictureContainer
 * Method:    addPicture
 * Signature: (Ljava/lang/String;II[II)V
 */
JNIEXPORT void JNICALL Java_com_ingenic_iwds_slpt_view_core_Picture_00024PictureContainer_addPicture
  (JNIEnv *, jclass, jstring, jint, jint, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
