/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ingenic_iwds_slpt_view_utils_KeyReader */

#ifndef _Included_com_ingenic_iwds_slpt_view_utils_KeyReader
#define _Included_com_ingenic_iwds_slpt_view_utils_KeyReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ingenic_iwds_slpt_view_utils_KeyReader
 * Method:    initialize_native
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_ingenic_iwds_slpt_view_utils_KeyReader_initialize_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ingenic_iwds_slpt_view_utils_KeyReader
 * Method:    recycle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ingenic_iwds_slpt_view_utils_KeyReader_recycle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ingenic_iwds_slpt_view_utils_KeyReader
 * Method:    readByte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_com_ingenic_iwds_slpt_view_utils_KeyReader_readByte
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ingenic_iwds_slpt_view_utils_KeyReader
 * Method:    readBoolean
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ingenic_iwds_slpt_view_utils_KeyReader_readBoolean
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ingenic_iwds_slpt_view_utils_KeyReader
 * Method:    readShort
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_ingenic_iwds_slpt_view_utils_KeyReader_readShort
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ingenic_iwds_slpt_view_utils_KeyReader
 * Method:    readInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ingenic_iwds_slpt_view_utils_KeyReader_readInt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ingenic_iwds_slpt_view_utils_KeyReader
 * Method:    readLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_ingenic_iwds_slpt_view_utils_KeyReader_readLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ingenic_iwds_slpt_view_utils_KeyReader
 * Method:    readFloat
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_ingenic_iwds_slpt_view_utils_KeyReader_readFloat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ingenic_iwds_slpt_view_utils_KeyReader
 * Method:    readDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_ingenic_iwds_slpt_view_utils_KeyReader_readDouble
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ingenic_iwds_slpt_view_utils_KeyReader
 * Method:    readString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ingenic_iwds_slpt_view_utils_KeyReader_readString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ingenic_iwds_slpt_view_utils_KeyReader
 * Method:    readByteArray
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ingenic_iwds_slpt_view_utils_KeyReader_readByteArray
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ingenic_iwds_slpt_view_utils_KeyReader
 * Method:    readBooleanArray
 * Signature: (J)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_com_ingenic_iwds_slpt_view_utils_KeyReader_readBooleanArray
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ingenic_iwds_slpt_view_utils_KeyReader
 * Method:    readShortArray
 * Signature: (J)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_ingenic_iwds_slpt_view_utils_KeyReader_readShortArray
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ingenic_iwds_slpt_view_utils_KeyReader
 * Method:    readIntArray
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_ingenic_iwds_slpt_view_utils_KeyReader_readIntArray
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ingenic_iwds_slpt_view_utils_KeyReader
 * Method:    readLongArray
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_ingenic_iwds_slpt_view_utils_KeyReader_readLongArray
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ingenic_iwds_slpt_view_utils_KeyReader
 * Method:    readFloatArray
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_ingenic_iwds_slpt_view_utils_KeyReader_readFloatArray
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ingenic_iwds_slpt_view_utils_KeyReader
 * Method:    readDoubleArray
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_ingenic_iwds_slpt_view_utils_KeyReader_readDoubleArray
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
